/**
 * .env.local file writer
 * Backs up any existing .env.local before writing new credentials
 */

import { copyFile, writeFile, access } from 'node:fs/promises'
import { chmod } from 'node:fs/promises'
import { join } from 'node:path'

export interface EnvVars {
  // Supabase
  DATABASE_URI?: string
  SUPABASE_URL?: string
  SUPABASE_ANON_KEY?: string
  SUPABASE_SERVICE_ROLE_KEY?: string
  // Cloudflare R2
  R2_BUCKET?: string
  R2_ENDPOINT?: string
  R2_PUBLIC_URL?: string
  R2_ACCESS_KEY_ID?: string
  R2_SECRET_ACCESS_KEY?: string
  R2_ACCOUNT_ID?: string
  // Payload
  PAYLOAD_SECRET?: string
  NEXT_PUBLIC_SERVER_URL?: string
  // Extra arbitrary vars
  [key: string]: string | undefined
}

/** Check if a file exists */
async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

/** Generate a random 32-char hex secret for PAYLOAD_SECRET */
export function generatePayloadSecret(): string {
  const bytes = new Uint8Array(32)
  crypto.getRandomValues(bytes)
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
}

/** Render env vars to file content with section comments */
function renderEnvContent(vars: EnvVars): string {
  const lines: string[] = [
    `# Generated by create-tree-id on ${new Date().toISOString()}`,
    '# DO NOT commit this file to version control',
    '',
  ]

  // Supabase section
  const supabaseKeys = ['DATABASE_URI', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY']
  const supabaseVars = supabaseKeys.filter((k) => vars[k] !== undefined)
  if (supabaseVars.length > 0) {
    lines.push('# --- Supabase ---')
    for (const key of supabaseVars) {
      lines.push(`${key}="${vars[key]}"`)
    }
    lines.push('')
  }

  // Cloudflare R2 section
  const r2Keys = ['R2_BUCKET', 'R2_ENDPOINT', 'R2_PUBLIC_URL', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY', 'R2_ACCOUNT_ID']
  const r2Vars = r2Keys.filter((k) => vars[k] !== undefined)
  if (r2Vars.length > 0) {
    lines.push('# --- Cloudflare R2 ---')
    for (const key of r2Vars) {
      lines.push(`${key}="${vars[key]}"`)
    }
    lines.push('')
  }

  // Payload / Next.js section
  const payloadKeys = ['PAYLOAD_SECRET', 'NEXT_PUBLIC_SERVER_URL']
  const payloadVars = payloadKeys.filter((k) => vars[k] !== undefined)
  if (payloadVars.length > 0) {
    lines.push('# --- Payload / Next.js ---')
    for (const key of payloadVars) {
      lines.push(`${key}="${vars[key]}"`)
    }
    lines.push('')
  }

  // Remaining / custom vars
  const knownKeys = new Set([...supabaseKeys, ...r2Keys, ...payloadKeys])
  const extraVars = Object.entries(vars).filter(([k, v]) => !knownKeys.has(k) && v !== undefined)
  if (extraVars.length > 0) {
    lines.push('# --- Other ---')
    for (const [key, value] of extraVars) {
      lines.push(`${key}="${value}"`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

/** Write .env.local to the given directory, backing up any existing file */
export async function writeEnvFile(targetDir: string, vars: EnvVars): Promise<string> {
  const envPath = join(targetDir, '.env.local')
  const backupPath = join(targetDir, '.env.local.backup')

  // Backup existing file
  if (await fileExists(envPath)) {
    await copyFile(envPath, backupPath)
  }

  const content = renderEnvContent(vars)
  await writeFile(envPath, content, 'utf-8')

  // Restrict permissions on Unix (chmod 600)
  if (process.platform !== 'win32') {
    await chmod(envPath, 0o600)
  }

  return envPath
}
