/**
 * Skill spec types — defines the portable Agent Skill specification
 * generated by Feature Builder's Plan step. Output is JSON, consumed
 * by Claude Code's /skill-creator to scaffold the actual skill folder.
 */

export interface SkillSpec {
  skill: SkillMetadata
  references: SkillFileEntry[]
  scripts: SkillFileEntry[]
  dataSchema: DataSchemaHint
  treeidIntegration: TreeIdIntegration
}

export interface SkillMetadata {
  /** kebab-case skill name derived from feature name */
  name: string
  /** Model-facing description for activation (not human summary) */
  description: string
  version: string
  /** SKILL.md body text — template-generated outline */
  body: string
}

export interface SkillFileEntry {
  filename: string
  purpose: string
}

export interface DataSchemaField {
  name: string
  type: 'text' | 'number' | 'boolean' | 'date' | 'rich-text'
  required: boolean
}

export interface DataSchemaHint {
  /** Raw dataDescription from user input */
  description: string
  suggestedFields: DataSchemaField[]
}

export interface TreeIdIntegration {
  section: string
  uiNeeds: string
  /** Admin UI component files to create */
  components: string[]
  /** API route files to create */
  apiRoutes: string[]
  /** Suggested feature-registry.ts entry */
  registryEntry: string
  navItem: { href: string; label: string; iconKey: string }
}
