// Auto-generated by `payload generate:importmap`
// Manually populated for S3 storage plugin client component
import { S3ClientUploadHandler } from '@payloadcms/storage-s3/client'

export const importMap = {
  '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler,
}
